arch: UKAN
batch_size: 8
cfg: null
data_dir: /content/test_Roweeder_complete
dataseed: 2981
dataset: roweeder
deep_supervision: false
early_stopping: -1
epochs: 400
factor: 0.1
gamma: 0.6666666666666666
input_channels: 3
input_h: 512
input_list:
- 64
- 80
- 128
input_w: 512
kan_lr: 0.01
kan_weight_decay: 0.0001
loss: CrossEntropyLoss
lr: 0.0001
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: roweeder_UKAN
nesterov: false
no_kan: false
num_classes: 3
num_workers: 4
optimizer: Adam
output_dir: /kaggle/working/
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
